version: '3.1'
services:
  springboot22api:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot22api:latest
    container_name: springboot
#    image: 'springboot22'
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSQL
#          condition: service_healthy
      - rabbitmq-container

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq-container:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
#    volumes:
#        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
#        - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    tty: true
    restart: always
